### ISSUE TITLE
You seem to have removed all the attribution notes for who actually made this code

### ISSUE THREAD

**Issue by SuspicousBell** [Tinychat/Tinychat-YouTube-Fix#2]
I see that you have (obviously, completely accidentally) removed the multiple attribution notes from this source code which you (obviously, by mistake) just randomly stumbled upon in pastebin.

I'm sure the real developer of this code (bell) is a lovely person, I don't know but it'd be nice to find out one day. So I'll just leave the original code which you lifted this from here: http://pastebin.com/6Pyp9p7g

In your html file you mistakingly have "<title>Ruddernation Designs</title>" which should be "<title>**Bell's** Tinychat / Youtube Hack Fix [python edition]</title>"

Also in this file you seem to have removed this javascript comment: "**Bell's** youtube (and more) hack for tinychat, variant for python poc so lacking most features"

And from the readme from the root directory which you've removed "Enjoy and adapt or whatever - **Bell**."

-----

It's not polite to just steal people's code, there's nothing wrong with taking people's code and improving upon it or changing it to your needs but by removing the original author of the code and just lying to people claiming you wrote it is probably one of the scummiest things a 'developer' can do, especially when you haven't actually improved the code (which isn't great consider bell is not a python developer and literally took half a day out of his busy schedule to port a feature for other people to use using an entirely different bot). A reputation as a thief won't go well for your career and I'm pretty sure if you had a job and your boss/company found you were lifting code, you wouldn't have your job much longer. Consider this your 'waking moment' of starting to attribute the authors of code you use in future.

**Comment by Ruddernation-Designs** [comment]
Talking about yourself in the 3rd person context is very idiotic, It's pretty obvious it's you 'Bell' and as for me adding Ruddernation Designs to the title does not mean I wrote the thing, Anything that I write or modify will have my title added to it as it's on my profile, I could of gone out and added Tinychat to it instead as this organisation is Tinychat, Don't go posting crap on peoples repositories because you decide something is yours or get pissed because someone never gave you a shout out, I don't know you and you don't know me and I couldn't give a shit, You have serious issues, If you don't want people using your shit then don't post it online and especially without a license, 
On a further note, Do you think Tinychat is going to get your new account banned? as that's what us companies do right!? Grow up.
